"""Added remediate_sqs_queue column to qj job table

Revision ID: 9d956e753055
Revises: 60990e9bc347
Create Date: 2021-09-22 10:11:51.243002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d956e753055'
down_revision = '60990e9bc347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('remediate_sqs_queue', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'remediate_sqs_queue')
    # ### end Alembic commands ###
